DROP TABLE dbo.__EFMigrationsHistory
DROP TABLE dbo.Announcements
DROP TABLE dbo.AspNetRoleClaims
DROP TABLE dbo.AspNetRoles
DROP TABLE dbo.AspNetUserClaims
DROP TABLE dbo.AspNetUserRoles
DROP TABLE dbo.AspNetUserLogins
DROP TABLE dbo.AspNetUsers
DROP TABLE dbo.AspNetUserTokens
DROP TABLE dbo.Auditoriums
DROP TABLE dbo.CinemaStudios
DROP TABLE dbo.Clients
DROP TABLE dbo.[Events]
DROP TABLE dbo.Images
DROP TABLE dbo.JobAdvertisements
DROP TABLE dbo.[Messages]
DROP TABLE dbo.MovieCreatorMovies
DROP TABLE dbo.MovieCreators
DROP TABLE dbo.MovieCreatorSpecialties
DROP TABLE dbo.MovieCreatorVotings
DROP TABLE dbo.Movies
DROP TABLE dbo.Orders
DROP TABLE dbo.Ratings
DROP TABLE dbo.Shows
DROP TABLE dbo.Specialties
DROP TABLE dbo.Subscriptions
DROP TABLE dbo.Theathers
DROP TABLE dbo.Videos
DROP TABLE dbo.Votes
DROP TABLE dbo.VotesAdmins
DROP TABLE dbo.Votings
